// Code generated by protoc-gen-go. DO NOT EDIT.
// source: things.proto

/*
Package things is a generated protocol buffer package.

It is generated from these files:
	things.proto

It has these top-level messages:
	Thing
	QueryThingsRequest
	ThingsResponse
	GetThingRequest
	CreateThingRequest
	UpdateThingRequest
	DeleteThingRequest
*/
package things

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Thing
type Thing struct {
	Id      uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Content []byte `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *Thing) Reset()                    { *m = Thing{} }
func (m *Thing) String() string            { return proto.CompactTextString(m) }
func (*Thing) ProtoMessage()               {}
func (*Thing) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Thing) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Thing) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Thing) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type QueryThingsRequest struct {
	Search string `protobuf:"bytes,1,opt,name=search" json:"search,omitempty"`
	Order  string `protobuf:"bytes,2,opt,name=order" json:"order,omitempty"`
	Limit  uint64 `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	Offset uint64 `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
}

func (m *QueryThingsRequest) Reset()                    { *m = QueryThingsRequest{} }
func (m *QueryThingsRequest) String() string            { return proto.CompactTextString(m) }
func (*QueryThingsRequest) ProtoMessage()               {}
func (*QueryThingsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *QueryThingsRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

func (m *QueryThingsRequest) GetOrder() string {
	if m != nil {
		return m.Order
	}
	return ""
}

func (m *QueryThingsRequest) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *QueryThingsRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

// Things, with an optional "next" token
type ThingsResponse struct {
	Things []*Thing `protobuf:"bytes,1,rep,name=things" json:"things,omitempty"`
	Next   string   `protobuf:"bytes,2,opt,name=next" json:"next,omitempty"`
}

func (m *ThingsResponse) Reset()                    { *m = ThingsResponse{} }
func (m *ThingsResponse) String() string            { return proto.CompactTextString(m) }
func (*ThingsResponse) ProtoMessage()               {}
func (*ThingsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ThingsResponse) GetThings() []*Thing {
	if m != nil {
		return m.Things
	}
	return nil
}

func (m *ThingsResponse) GetNext() string {
	if m != nil {
		return m.Next
	}
	return ""
}

type GetThingRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetThingRequest) Reset()                    { *m = GetThingRequest{} }
func (m *GetThingRequest) String() string            { return proto.CompactTextString(m) }
func (*GetThingRequest) ProtoMessage()               {}
func (*GetThingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetThingRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CreateThingRequest struct {
	Thing *Thing `protobuf:"bytes,1,opt,name=thing" json:"thing,omitempty"`
}

func (m *CreateThingRequest) Reset()                    { *m = CreateThingRequest{} }
func (m *CreateThingRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateThingRequest) ProtoMessage()               {}
func (*CreateThingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreateThingRequest) GetThing() *Thing {
	if m != nil {
		return m.Thing
	}
	return nil
}

type UpdateThingRequest struct {
	Thing *Thing `protobuf:"bytes,1,opt,name=thing" json:"thing,omitempty"`
}

func (m *UpdateThingRequest) Reset()                    { *m = UpdateThingRequest{} }
func (m *UpdateThingRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateThingRequest) ProtoMessage()               {}
func (*UpdateThingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UpdateThingRequest) GetThing() *Thing {
	if m != nil {
		return m.Thing
	}
	return nil
}

type DeleteThingRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteThingRequest) Reset()                    { *m = DeleteThingRequest{} }
func (m *DeleteThingRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteThingRequest) ProtoMessage()               {}
func (*DeleteThingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DeleteThingRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Thing)(nil), "things.Thing")
	proto.RegisterType((*QueryThingsRequest)(nil), "things.QueryThingsRequest")
	proto.RegisterType((*ThingsResponse)(nil), "things.ThingsResponse")
	proto.RegisterType((*GetThingRequest)(nil), "things.GetThingRequest")
	proto.RegisterType((*CreateThingRequest)(nil), "things.CreateThingRequest")
	proto.RegisterType((*UpdateThingRequest)(nil), "things.UpdateThingRequest")
	proto.RegisterType((*DeleteThingRequest)(nil), "things.DeleteThingRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Things service

type ThingsClient interface {
	// List any number of things
	List(ctx context.Context, in *QueryThingsRequest, opts ...grpc.CallOption) (*ThingsResponse, error)
	// Get a single thing
	Get(ctx context.Context, in *GetThingRequest, opts ...grpc.CallOption) (*Thing, error)
	// Create and return a new thing
	Create(ctx context.Context, in *CreateThingRequest, opts ...grpc.CallOption) (*Thing, error)
	// Update and return an existing thing
	Update(ctx context.Context, in *UpdateThingRequest, opts ...grpc.CallOption) (*Thing, error)
	// Delete a thing
	Delete(ctx context.Context, in *DeleteThingRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	// Query is not exposed to the bridge, but allows streaming of things
	Query(ctx context.Context, in *QueryThingsRequest, opts ...grpc.CallOption) (Things_QueryClient, error)
}

type thingsClient struct {
	cc *grpc.ClientConn
}

func NewThingsClient(cc *grpc.ClientConn) ThingsClient {
	return &thingsClient{cc}
}

func (c *thingsClient) List(ctx context.Context, in *QueryThingsRequest, opts ...grpc.CallOption) (*ThingsResponse, error) {
	out := new(ThingsResponse)
	err := grpc.Invoke(ctx, "/things.Things/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thingsClient) Get(ctx context.Context, in *GetThingRequest, opts ...grpc.CallOption) (*Thing, error) {
	out := new(Thing)
	err := grpc.Invoke(ctx, "/things.Things/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thingsClient) Create(ctx context.Context, in *CreateThingRequest, opts ...grpc.CallOption) (*Thing, error) {
	out := new(Thing)
	err := grpc.Invoke(ctx, "/things.Things/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thingsClient) Update(ctx context.Context, in *UpdateThingRequest, opts ...grpc.CallOption) (*Thing, error) {
	out := new(Thing)
	err := grpc.Invoke(ctx, "/things.Things/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thingsClient) Delete(ctx context.Context, in *DeleteThingRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/things.Things/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thingsClient) Query(ctx context.Context, in *QueryThingsRequest, opts ...grpc.CallOption) (Things_QueryClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Things_serviceDesc.Streams[0], c.cc, "/things.Things/Query", opts...)
	if err != nil {
		return nil, err
	}
	x := &thingsQueryClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Things_QueryClient interface {
	Recv() (*Thing, error)
	grpc.ClientStream
}

type thingsQueryClient struct {
	grpc.ClientStream
}

func (x *thingsQueryClient) Recv() (*Thing, error) {
	m := new(Thing)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Things service

type ThingsServer interface {
	// List any number of things
	List(context.Context, *QueryThingsRequest) (*ThingsResponse, error)
	// Get a single thing
	Get(context.Context, *GetThingRequest) (*Thing, error)
	// Create and return a new thing
	Create(context.Context, *CreateThingRequest) (*Thing, error)
	// Update and return an existing thing
	Update(context.Context, *UpdateThingRequest) (*Thing, error)
	// Delete a thing
	Delete(context.Context, *DeleteThingRequest) (*google_protobuf1.Empty, error)
	// Query is not exposed to the bridge, but allows streaming of things
	Query(*QueryThingsRequest, Things_QueryServer) error
}

func RegisterThingsServer(s *grpc.Server, srv ThingsServer) {
	s.RegisterService(&_Things_serviceDesc, srv)
}

func _Things_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryThingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThingsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/things.Things/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThingsServer).List(ctx, req.(*QueryThingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Things_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetThingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThingsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/things.Things/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThingsServer).Get(ctx, req.(*GetThingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Things_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateThingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThingsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/things.Things/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThingsServer).Create(ctx, req.(*CreateThingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Things_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateThingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThingsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/things.Things/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThingsServer).Update(ctx, req.(*UpdateThingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Things_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteThingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThingsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/things.Things/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThingsServer).Delete(ctx, req.(*DeleteThingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Things_Query_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryThingsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ThingsServer).Query(m, &thingsQueryServer{stream})
}

type Things_QueryServer interface {
	Send(*Thing) error
	grpc.ServerStream
}

type thingsQueryServer struct {
	grpc.ServerStream
}

func (x *thingsQueryServer) Send(m *Thing) error {
	return x.ServerStream.SendMsg(m)
}

var _Things_serviceDesc = grpc.ServiceDesc{
	ServiceName: "things.Things",
	HandlerType: (*ThingsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Things_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Things_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Things_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Things_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Things_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Query",
			Handler:       _Things_Query_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "things.proto",
}

func init() { proto.RegisterFile("things.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 466 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x40, 0x71, 0xe2, 0x18, 0x75, 0x08, 0xad, 0x18, 0x20, 0x35, 0x06, 0xa1, 0xb0, 0x14, 0xc9,
	0xe2, 0x60, 0x43, 0x90, 0x90, 0xe0, 0x0a, 0xa5, 0x07, 0x50, 0x25, 0x2c, 0x7a, 0xe0, 0xe8, 0xd6,
	0x93, 0x74, 0xa5, 0x64, 0xd7, 0x78, 0x37, 0xa8, 0x15, 0xea, 0x85, 0x5f, 0xe0, 0xd3, 0xb8, 0x71,
	0xe6, 0x43, 0x90, 0x77, 0xd7, 0x75, 0x63, 0x4b, 0x1c, 0x7a, 0x4a, 0xc6, 0x3b, 0xf3, 0x66, 0xf6,
	0x8d, 0x16, 0xc6, 0xfa, 0x94, 0x8b, 0x85, 0x4a, 0xca, 0x4a, 0x6a, 0x89, 0x81, 0x8d, 0xa2, 0x47,
	0x0b, 0x29, 0x17, 0x4b, 0x4a, 0xf3, 0x92, 0xa7, 0xb9, 0x10, 0x52, 0xe7, 0x9a, 0x4b, 0xe1, 0xb2,
	0xa2, 0x87, 0xee, 0xd4, 0x44, 0xc7, 0xeb, 0x79, 0x4a, 0xab, 0x52, 0x9f, 0xdb, 0x43, 0xb6, 0x0f,
	0xa3, 0x2f, 0x35, 0x04, 0xb7, 0x61, 0xc0, 0x8b, 0xd0, 0x9b, 0x7a, 0xb1, 0x9f, 0x0d, 0x78, 0x81,
	0x08, 0xbe, 0xc8, 0x57, 0x14, 0x0e, 0xa6, 0x5e, 0xbc, 0x95, 0x99, 0xff, 0x18, 0xc2, 0xcd, 0x13,
	0x29, 0x34, 0x09, 0x1d, 0x0e, 0xa7, 0x5e, 0x3c, 0xce, 0x9a, 0x90, 0x95, 0x80, 0x9f, 0xd7, 0x54,
	0x9d, 0x1b, 0x96, 0xca, 0xe8, 0xdb, 0x9a, 0x94, 0xc6, 0x09, 0x04, 0x8a, 0xf2, 0xea, 0xe4, 0xd4,
	0x70, 0xb7, 0x32, 0x17, 0xe1, 0x3d, 0x18, 0xc9, 0xaa, 0xa0, 0xca, 0xc1, 0x6d, 0x50, 0x7f, 0x5d,
	0xf2, 0x15, 0xb7, 0x6c, 0x3f, 0xb3, 0x41, 0xcd, 0x90, 0xf3, 0xb9, 0x22, 0x1d, 0xfa, 0xe6, 0xb3,
	0x8b, 0xd8, 0x47, 0xd8, 0x6e, 0x9a, 0xa9, 0x52, 0x0a, 0x45, 0xf8, 0x0c, 0x9c, 0x8f, 0xd0, 0x9b,
	0x0e, 0xe3, 0x5b, 0xb3, 0xdb, 0x89, 0x93, 0x65, 0xf2, 0x32, 0x77, 0x68, 0x2e, 0x46, 0x67, 0xfa,
	0xf2, 0x62, 0x74, 0xa6, 0xd9, 0x13, 0xd8, 0x39, 0x20, 0x6d, 0xf3, 0xdc, 0xec, 0x1d, 0x1f, 0xec,
	0x0d, 0xe0, 0xbb, 0x8a, 0x72, 0x4d, 0x1b, 0x59, 0x4f, 0x61, 0x64, 0xb0, 0x26, 0xb1, 0xd7, 0xd2,
	0x9e, 0xd5, 0xa5, 0x47, 0x65, 0x71, 0xad, 0xd2, 0x3d, 0xc0, 0xf7, 0xb4, 0xa4, 0x4e, 0x69, 0x67,
	0xb6, 0xd9, 0x9f, 0x21, 0x04, 0x56, 0x06, 0x1e, 0x82, 0xff, 0x89, 0x2b, 0x8d, 0x51, 0x83, 0xeb,
	0xaf, 0x25, 0x9a, 0x6c, 0xb4, 0xba, 0x14, 0xc8, 0xf0, 0xe7, 0xef, 0xbf, 0xbf, 0x06, 0x63, 0x84,
	0xf4, 0xfb, 0xcb, 0xd4, 0xd9, 0xfa, 0x00, 0xc3, 0x03, 0xd2, 0xb8, 0xdb, 0x94, 0x74, 0x34, 0x45,
	0x9b, 0x63, 0xb3, 0x5d, 0x83, 0xb8, 0x83, 0x3b, 0x2d, 0x22, 0xfd, 0xc1, 0x8b, 0x0b, 0x3c, 0x84,
	0xc0, 0xea, 0x6b, 0x27, 0xeb, 0xeb, 0xec, 0xd2, 0x1e, 0x18, 0xda, 0x5d, 0x76, 0x65, 0xa0, 0xb7,
	0x56, 0x0c, 0x7e, 0x85, 0xc0, 0x3a, 0x6d, 0x79, 0x7d, 0xc7, 0x5d, 0xde, 0x9e, 0xe1, 0x3d, 0x9e,
	0xdd, 0xbf, 0x3a, 0x9d, 0xf9, 0x4d, 0x78, 0x71, 0xd1, 0xa0, 0x8f, 0x20, 0xb0, 0xce, 0x5b, 0x74,
	0x7f, 0x07, 0xd1, 0x24, 0xb1, 0xcf, 0x2a, 0x69, 0x9e, 0x55, 0xb2, 0x5f, 0x3f, 0xab, 0xc6, 0xc0,
	0xf3, 0x9e, 0x81, 0xd7, 0x30, 0x32, 0xbb, 0xf8, 0xef, 0x6a, 0x3a, 0x03, 0xdf, 0x78, 0xe1, 0x1d,
	0x07, 0xa6, 0xc1, 0xab, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x19, 0x33, 0x62, 0xfb, 0x03,
	0x00, 0x00,
}
